replicaCount: 1
image:
  repository: alpine/helm:3.11.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: backend-service-account

service:
  port: 8080

ingress:
  enabled: true

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

testConnection:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 5

nodeGroupName: "InternalServices"
