apiVersion: v1
kind: Secret
metadata:
  name: pizza-secret
type: Opaque
data:
  SERVICE_SECRET_KEY: Mm9lY1I0dFlqN1daNWdBZVhuRDlwSG1UYlZxMXNLZkU=
  rabbitmq-username: dXNlcg==
  rabbitmq-password: cGFzc3dvcmQ=
  mongodb-root-password: cm9vdHBhc3N3b3Jk
  mongodb-username: dXNlcg==
  mongodb-password: cGFzc3dvcmQ=
