apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        env:
        - name: RABBITMQ_URL
          value: "{{ .Values.rabbitmq.host | default 'my-rabbitmq' }}"
        - name: MONGODB_USERNAME
          value: "{{ .Values.mongodb.mongodbUsername }}"
        - name: MONGODB_PASSWORD
          value: "{{ .Values.mongodb.mongodbPassword }}"
        - name: MONGO_URL
          value: "mongodb://{{ .Values.mongodb.mongodbUsername }}:{{ .Values.mongodb.mongodbPassword }}@my-mongodb:27017/pizza_db"
        - name: SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pizza-secret
              key: SERVICE_SECRET_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
